-- NARRATIVE.WAR — Initial schema
-- Run this in the Supabase SQL Editor: https://app.supabase.com → SQL Editor

CREATE TABLE IF NOT EXISTS projects (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  topic           TEXT NOT NULL,
  model           TEXT NOT NULL,
  radar_output    TEXT,
  research_dossier TEXT,
  structure_map   TEXT,
  thumbnail_concept TEXT,
  script          JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);

-- Enable Row Level Security (optional — allows future per-user access control)
-- ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
